version: "3.9"

services:
  discovery:
    image: consul:1.15
    ports:
      - 8500:8500
    networks:
      - keycloak-network

  config-server:
    build: ./config
    environment:
      - SERVER_PORT=8888
      - GIT_URI=https://github.com/Clemguy45/projetTournoi.git
      - DEBUG=true
    depends_on:
      - discovery
    networks:
      - keycloak-network

  gateway:
    build: ./gateway
    ports:
      - 8082:8082
    environment:
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - DEBUG=true
    depends_on:
      - discovery
    networks:
      - keycloak-network


  mysql_tournois:
    image: mysql:8.0
    container_name: mysql_tournois
    environment:
      MYSQL_DATABASE: tournois
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - keycloak-network


  service_tournois:
    build: ./serviceTournois
    environment:
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_tournois:3306/tournois
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
    ports:
      - "8084:8080"
    depends_on:
      - mysql_tournois
      - discovery
      - config-server
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
