version: "3.9"

services:
  discovery:
    image: consul:1.15
    ports:
      - 8500:8500
    networks:
      - keycloak-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - keycloak-network

  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=MYSQL
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - DB_ADDR=mysql
    ports:
      - "8000:8080"
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
    command: [ "-b", "0.0.0.0", "-Dkeycloak.import=/tmp/realm-export.json" ]
    networks:
      - keycloak-network

  config-server:
    build: ./config
    environment:
      - SERVER_PORT=8888
      - GIT_URI=https://github.com/Clemguy45/projetTournoi.git
      - DEBUG=true
    depends_on:
      - discovery
    networks:
      - keycloak-network

  gateway:
    build: ./gateway
    ports:
      - 8082:8082
    environment:
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - DEBUG=true
    depends_on:
    - discovery
    networks:
      - keycloak-network

  joueur:
    build: ./serviceJoueur
    environment:
      - DEBUG=true
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/keycloak
      - SPRING_DATASOURCE_USERNAME=keycloak
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
    depends_on:
      - discovery
      - config-server
      - mysql
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local