version: "3.9"

services:
  discovery:
    image: consul:1.15.4
    ports:
      - 8500:8500

  keycloack:
    image: jboss/keycloak:latest
    ports:
      - 8000:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - BEBUG = true
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
    command: ["-b", "0.0.0.0", "-Dkeycloak.import=/tmp/realm-export.json"]

  config-server:
    build: ./config
    environment:
      - SERVER_PORT=8888
      - GIT_URI=https://github.com/Clemguy45/projetTournoi.git
      - DEBUG=true
    depends_on:
      - discovery

  gateway:
    build: ./gateway
    ports:
      - 8082:8082
    environment:
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - DEBUG=true
    depends_on:
      - discovery
