version: "3.9"

services:
  discovery:
    image: consul:1.15
    ports:
      - 8500:8500
    networks:
      - keycloak-network

  mysql-tournoi:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: tournoi
      MYSQL_USER: tournoi
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - keycloak-network

  config-server:
    build: ./config
    environment:
      - SERVER_PORT=8888
      - GIT_URI=https://github.com/Clemguy45/projetTournoi.git
      - DEBUG=true
    depends_on:
      - discovery
    networks:
      - keycloak-network

  gateway:
    build: ./gateway
    ports:
      - 8082:8082
    environment:
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - DEBUG=true
    depends_on:
      - discovery
    networks:
      - keycloak-network

  tournoi:
    build: ./tournoi
    environment:
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-tournoi:3306/tournoi
      - SPRING_DATASOURCE_USERNAME=tournoi
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
    depends_on:
      - discovery
      - config-server
      - mysql-tournoi
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local