version: "3.9"

services:
  discovery:
    image: consul:1.15
    ports:
      - 8500:8500
    networks:
      - keycloak-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: joueur
      MYSQL_USER: joueurAdmin
      MYSQL_PASSWORD: joueurAdminPassword
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - keycloak-network

  config-server:
    build: ./config
    environment:
      - SERVER_PORT=8888
      - GIT_URI=https://github.com/Clemguy45/projetTournoi.git
      - DEBUG=true
    depends_on:
      - discovery
    networks:
      - keycloak-network

  gateway:
    build: ./gateway
    ports:
      - 8082:8082
    environment:
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - DEBUG=true
    depends_on:
      - discovery
    networks:
      - keycloak-network

  joueur:
    build: ./serviceJoueur
    environment:
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/joueur
      - SPRING_DATASOURCE_USERNAME=joueurAdmin
      - SPRING_DATASOURCE_PASSWORD=joueurAdminPassword
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
    depends_on:
      - discovery
      - config-server
      - mysql
    restart: always
    networks:
      - keycloak-network

  mysql_jeux:
    image: mysql:8.0
    container_name: mysql_jeux
    environment:
      MYSQL_DATABASE: jeux
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql-data_jeux:/var/lib/mysql
    networks:
      - keycloak-network

  service_jeux:
    build: ./serviceJeux
    ports:
      - 8085:8085
    environment:
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_jeux:3306/jeux
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
    depends_on:
      - discovery
      - mysql_jeux
      - config-server
    networks:
      - keycloak-network
    restart: always

  mysql_tournois:
    image: mysql:8.0
    container_name: mysql_tournois
    environment:
      MYSQL_DATABASE: tournois
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data_tournois:/var/lib/mysql
    networks:
      - keycloak-network


  service_tournois:
    build: ./serviceTournois
    environment:
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_tournois:3306/tournois
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
    ports:
      - "8084:8080"
    depends_on:
      - mysql_tournois
      - discovery
      - config-server
    restart: always
    networks:
      - keycloak-network

  chatservice:
    image: chatservice
    build: ./ChatService
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql_message
      - DB_PORT=3306
      - DB_NAME=message
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - mysql_message
      - discovery
      - config-server
    networks:
      - keycloak-network
    restart: always


  mysql_message:
    image: mysql:8.0
    container_name: mysql_message
    environment:
      MYSQL_DATABASE: message
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - mysql-data_message:/var/lib/mysql

networks:
  keycloak-network:
    driver: bridge

volumes:
  mysql-data_tournois:
    driver: local
  mysql-data:
    driver: local
  mysql-data_jeux:
    driver: local
  mysql-data_message:
    driver: local