spring:
  application:
    name: gateway

  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        register: true
      ribbon:
        enabled: false

    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: joueur-service
          uri: lb://joueur-service
          predicates:
            - Path=/joueur/**
          filters:
            - RewritePath=/joueur/(?<path>.*), /joueur/$\{path}
            - PreserveHostHeader=true

server:
  port: 8082
