spring:
  application:
    name: gateway

  cloud:
    consul:
      discovery:
        register: true
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      ribbon:
        enabled: false

    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: tournois-service
          uri: lb://tournois-service
          predicates:
            - Path=/tournoi/**
          filters:
            - RewritePath=/tournoi/(?<path>.*), /tournoi/$\{path}
            - PreserveHostHeader=true

server:
  port: 8082