spring:
  application:
    name: gateway

  cloud:
    consul:
      discovery:
        register: true
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      ribbon:
        enabled: false



server:
  port: 8082