spring:
  application:
    name: gateway

  cloud:
    consul:
      discovery:
        register: true
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      ribbon:
        enabled: false

    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: serviceTournois
          uri: lb://serviceTournois
          predicates:
            - Path=/tournois/**
          filters:
            - RewritePath=/tournois/(?<path>.*), /tournois/$\{path}
            - PreserveHostHeader=true

server:
  port: 8082