spring:
  application:
    name: gateway

  cloud:
    consul:
      discovery:
        register: true
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      ribbon:
        enabled: false

    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: jeuxtri
          uri: lb://jeuxtri
          predicates:
            - Path=/jeuxtri/**
          filters:
            - RewritePath=/jeuxtri/(?<path>.*), /jeuxtri/$\{path}
            - PreserveHostHeader=true


server:
  port: 8082